services:

  client:
    build: ./client
    container_name: client
    ports:
      - 80:80
    depends_on:
      - server

  server:
    build: ./server
    container_name: server
    ports:
      - 5000:5000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb_server
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
